### ISSUE TITLE
armv7hl: Error: bad instruction `bsfl [r5],r1`

### ISSUE THREAD

**Issue by matwey** [saleyn/eixx#19]
When compiling on armv7hl I have the following:

```
[  761s] /tmp/ccv1DxyP.s: Assembler messages:
[  761s] /tmp/ccv1DxyP.s:154954: Error: bad instruction `bsfl [r5],r1'
[  769s] Makefile:673: recipe for target 'test_node-test_node.o' failed
```

Not all platforms have```bsf*``` instructions, but some of them (for instance aarch64) seem to have alternatives.
```
static __inline__ unsigned long bit_scan_forward(unsigned long v)
{
    unsigned long r;
    __asm__ __volatile__(
        #if (__SIZEOF_LONG__ == 8)
            "bsfq %1, %0": "=r"(r): "rm"(v) );
        #else
            "bsfl %1, %0": "=r"(r): "rm"(v) );
        #endif
    return r;
}
```
Also, why don't just use things like ```__builtin_ffsl``` which will allow compiler to handle proper implementation on all platforms?

**Comment by matwey** [comment]
Moreover, I am not sure that it makes sense but current implementation doesn't make difference between ``0x0`` and ``0x1`` returning 0 in both cases.

**Comment by matwey** [comment]
Please, look at https://goo.gl/vS3hJT
```__builtin_ctzl``` generates same assembler like yours both for gcc and clang, but supports all platforms.

**Comment by matwey** [comment]
See possible implementation in PR #18

**Comment by saleyn** [comment]
At the time of writing eixx gcc didn't have these built-in functions, so I had to use assembler.  I certainly don't mind switching to build-ins since now it's no longer an issue.

**Comment by saleyn** [comment]
Actually it looks like __builtin_ctzl(0) = 64.  I am not sure if this is an issue, need to check the impact...

**Comment by matwey** [comment]
__builtin_ctzl(0) is UB:

>— Built-in Function: int __builtin_ctz (unsigned int x)
>
>    Returns the number of trailing 0-bits in x, starting at the least significant bit position. If x is 0, the result is undefined.

**Comment by saleyn** [comment]
Can you submit the PR for __builtin_ffsl? Also, to make it deterministic, transport_msg::to_type() should return:
m_type == UNDEFINED ? 0 : bit_scan_forward(m_type)
