### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fenollp** [saleyn/eixx#21]
Hi. On Travis CI's architecture (Ubuntu 12 LTS I believe) I get
```
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
./configure: line 3302: syntax error near unexpected token `noext,'
./configure: line 3302: `         AX_CXX_COMPILE_STDCXX_11(noext, optional)'
```

My .travis.yml file: https://github.com/fenollp/eixx/blob/6f22bbcee0ae0a2dcb591f0b00a2936ffda70a58/.travis.yml
Do I need to install something?

**Comment by saleyn** [comment]
Do you have autoconf-archive package installed?

**Comment by fenollp** [comment]
@saleyn It does here: https://github.com/saleyn/eixx/blob/master/configure.ac#L59-L63

**Comment by saleyn** [comment]
Sorry, I was looking at a stale branch. The macro is part of autoconf-archive.

**Comment by fenollp** [comment]
Using a newer distrib fixed the issue (Trusty)
