### ISSUE TITLE
INSTALL cannot find libeixx_d.so.1.4

### ISSUE THREAD

**Issue by matwey** [saleyn/eixx#26]
Hello,

I do the following commands:

```
make -j8 distclean
make -j8 bootstrap prefix=/usr build=Release
make -j8 verbose=true
make install DESTDIR=/home/abuild/rpmbuild/BUILDROOT/eixx-1.4+git20160510.cd24f3d-1.1.x86_64
```

```
[  162s] CMake Error at src/cmake_install.cmake:58 (file):
[  162s]   file INSTALL cannot find
[  162s]   "/home/abuild/rpmbuild/BUILD/eixx-1.4+git20160510.cd24f3d/build/src/libeixx_d.so.1.4".
[  162s] Call Stack (most recent call first):
[  162s]   cmake_install.cmake:92 (include)
[  162s]   
[  162s] 
[  162s] 
[  162s] Makefile:71: recipe for target 'install' failed
[  162s] make[1]: *** [install] Error 1
[  162s] Makefile:47: recipe for target 'install' failed
[  162s] make: *** [install] Error 2
```

**Comment by saleyn** [comment]
I haven't figured out how to force cmake build targets for both "debug" and "release" in one pass.

The "release" installer also tried to install a "debug version of the library (i.e. libeixx_d.so), which needs to be explicitly built.

Try this:
make bootstrap prefix=/usr build=debug
make src/libeixx_d.so
make rebootstrap build=release
make
make install

**Comment by matwey** [comment]
Why do you want to build both targets in one pass? As far as I know, nobody does this with cmake.

**Comment by saleyn** [comment]
Ideally I want to make sure that when release install is done, both release and debug versions of the library get installed.  I haven't found an easier way to do that with cmake other than what I described above.
