### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by michaelkschmidt** [saleyn/eixx#29]
Most of the files have a GPL header, but the LICENSE file indicates Apache 2.0.  Has the license changed to Apache 2.0?

Sorry to have to ask, but we were hoping to use it in a non GPL project.

**Comment by saleyn** [comment]
I was planning to convert the project to Apache 2.0 license, but have completed updating all the files yet.

**Comment by saleyn** [comment]
Fixed.
