### ISSUE TITLE
Will this project be updated?

### ISSUE THREAD

**Issue by natewilly** [saleyn/eixx#31]
This is a great project, but it's not being updated for compatibility with (currently) OTP 21/OTP 20. I have to downgrade my erlang version in order to use eixx, since my c++ node created using eixx doesn't accept UTF-8 atoms. There are probably other issues too, but this is the error I got running the example and so I stopped there. This is the best c++ to erlang connection tool I have found so far, and much better than the options on the official docs. I think it has a lot of potential if it is kept up-to-date, especially since newer companies like Discord are starting to use Erlang more. So this is simply a request that that happen. It would be nice.

**Comment by saleyn** [comment]
Presently, upgrading it is somewhat low on my priority list as there are other paid projects I am focusing on.  Can't guarantee this will happen before the end of this year. Patches are welcome.

**Comment by saleyn** [comment]
The current version is compatible with OTP 23.
