### ISSUE TITLE
Why "Temporary disable support for a C++ erlang node"

### ISSUE THREAD

**Issue by heri16** [saleyn/eixx#41]
14 months ago, there was a commit message that says "Temporary disable support for a C++ erlang node."

https://github.com/saleyn/eixx/blob/2253d6417b386086b43291c55444c4e620177ee1/include/eixx/eixx.hpp#L62

Is this still disabled? What is the rationale or reasoning for this feature removal?

**Comment by saleyn** [comment]
With later versions of BOOST I was getting some segfaults, which I had no time to review and fix.  You are welcome to uncomment and submit patches if you can make it work.

**Comment by heri16** [comment]
Thanks for the update! I'll try to make it work.

Would the latest working version be Boost 1.59 or Boost 1.64?

https://github.com/saleyn/eixx/blob/c5b3d8f6580f054070b93147abde762577be3998/src/basic_otp_node_local.cpp#L22

**Comment by saleyn** [comment]
I don't quite recall. Haven't used that part of code for several years. Only have been using the marshaling part.

**Comment by heri16** [comment]
Any production use of this library? So our management can be see a good future for this open-source code, rather than using ei directly.

**Comment by saleyn** [comment]
The marshaling part of the library is being used is several production projects. The node connectivity part was used in production several years ago, until that system removed dependency on boost ASIO, at which point there was no solid need to maintain that compatibility in `eixx`.  If needed to revive it, I can do so on consulting basis, or you can do it yourself, and send patches.
